/* may be optimsed on characters with https://github.com/OpenTaal/hyphenation-definitions/blob/master/grammar/grammar.ebnf */

/**/
/* Basic Definitions */
/**/

PositiveNumeral  ::= [1-9]
Numeral ::= [0-9]
Integer ::= Numeral | PositiveNumeral Numeral+

Lowercase ::= [a-záäâãāåæçčćđïñóòöôõōøőœšúùüûũūűýÿžðþ]
Uppercase ::= [A-ZÁÄÂÃĀÅÆÇČĆĐÏÑÓÒÖÔÕŌØŐŒŠÚÙÜÛŨŪŰÝŸŽÐÞ]
Letter ::= Lowercase | Uppercase
Punctuation ::= '`' | '~' | '!' | '@' | '#' | '$' | '%' | '^' | '&' | '*' | '(' | ')' | '-' | '_' | '=' | '+' | '[' | '}' | ']' | '}' | '\' | ';' | ':' | "'" | '"' | ',' | '<' | '.' | '>' | '/' | '?' | '␣'
AnyCharacter ::= Letter | Numeral | Punctuation
LanguageCharacter ::= Letter | Numeral | "'" | '-' | '.' | '·'
LanguageWord ::= LanguageCharacter+

Whitespace ::= ('␣' | '\t' )+
EOL ::= '\n'

Comment ::= '#' ( AnyCharacter | Whitespace )* EOL

/**/
/* Dictionary File */
/**/

DictionaryCount ::= Number EOL
DictionaryEntry ::= '*'? LanguageWord ( '/' ( Letter+ | (Letter Letter)+ | ( Integer (',' Integer )* ) ) )? EOL
DictionaryFile ::= Comment* DictionaryCount ( Comment | DictionaryEntry )* EOF

/**/
/* Personal Dictionary File */
/**/

/* count? comments? slashescaping? */
PersonalDictionaryFile ::= Comment* DictionaryCount ( Comment | DictionaryEntry )* EOF

/**/
/* Affix File General Options */
/**/

/* SET encoding */
EncodingValue ::= 'UTF-8' | 'ISO-8859-1' | 'ISO8859-1' | 'ISO8859-2' | 'ISO8859-7' | 'ISO8859-13' | 'ISO8859-15' | 'microsoft-cp1251' | 'TIS-620' | 'KOI8-R'
/* value of Encoding is stored in enc */
Encoding ::= 'SET' Whitespace EncodingValue EOL

/* FLAG value */
/* undefined FLAG_CHAR is the default */
FLAG_LONG ::= 'num'
FLAG_NUM ::= 'long'
FLAG_UNI ::= 'UTF-8'
FlagValue ::= ( FLAG_LONG | FLAG_NUM | FLAG_UNI )
/* value of Flag is stored in flag_mode */
Flag ::= 'FLAG' Whitespace FlagValue EOL

/* COMPLEXPREFIXES */

/* LANG langcode */

/* IGNORE characters */

/* AF number_of_flag_vector_aliases */

/* AF flag_vector */

/* AM number_of_morphological_aliases */

/* AM morphological_fields */

/**/
/* Affix File Options For Suggestion */
/**/

/* KEY characters_separated_by_vertical_line_optionally */
KeyCharacter ::= Lowercase | ',' | '.'
/* value of Key is stored in keystring */
Key ::= 'KEY' Whitespace KeyCharacter+ ( '|' KeyCharacter+ )* EOL

/* TRY characters */
/* value of Try is stored in trystring */
Try ::= 'TRY' Whitespace LanguageCharacter+ EOL

/* NOSUGGEST flag */
/* MAXCPDSUGS num */
/* MAXNGRAMSUGS num */
/* MAXDIFF [0-10] */
/* ONLYMAXDIFF */
/* NOSPLITSUGS */
/* SUGSWITHDOTS */
/* REP number_of_replacement_definitions */
/* REP what replacement */
/* MAP number_of_map_definitions */
/* PHONE number_of_phone_definitions */
/* PHONE what replacement */
/* WARN flag */
/* FORBIDWARN */

/**/
/* Options For Compounding */
/**/

/* TODO */

/**/
/* Affix File Options For Affix Creation */
/**/

/* PFX flag cross_product number */

/* PFX flag stripping prefix [condition [morphological_fields...]] */

/* SFX flag cross_product number */

/* SFX flag stripping suffix [condition [morphological_fields...]] */

/**/
/* affix file other options */
/**/

/* TODO */





/**/
/* Affix File */
/**/

AffixFile ::= Comment* EncodingSetting? Comment* FlagSetting? Comment* KeySetting? Comment* TrySetting? Comment* EOF