/* may be optimsed on characters with https://github.com/OpenTaal/hyphenation-definitions/blob/master/grammar/grammar.ebnf */

PositiveNumeral  ::= '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'
Numeral ::= '0' | PositiveNumeral
Number ::= Numeral | PositiveNumeral Numeral+

LowercaseCharacter  ::= 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z' | 
UppercaseCharacter ::= 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z'
LetterCharacter ::= LowercaseCharacter | UppercaseCharacter
ASCIICharacter ::= Numeral | LetterCharacter | '`' | '~' | '!' | '@' | '#' | '$' | '%' | '^' | '&' | '*' | '(' | ')' | '-' | '_' | '=' | '+' | '[' | '}' | ']' | '}' | '\' | ';' | ':' | "'" | '"' | ',' | '<' | '.' | '>' | '/' | '?' | '␣'
Whitespace ::= ('␣' | '\t' )+

LanguageCharacter ::= LetterCharacter
LanguageWord ::= WordCharacter+

EOL ::= '\n'
Comment ::= '#' ( ASCIICharacter | Whitespace )* EOL

DictionaryCount ::= Number EOL
DictionaryEntry ::= '*'? LanguageWord ( '/' ( LetterCharacter+ | (LetterCharacter LetterCharacter)+ | ( Number (',' Number )* ) ) )? EOL
DictionaryFile ::= Comment* DictionaryCount ( Comment | DictionaryEntry )*

Encoding ::= 'UTF-8' | 'ISO-8859-1' | 'ISO8859-1' | 'ISO8859-2' | 'ISO8859-7' | 'ISO8859-13' | 'ISO8859-15' | 'microsoft-cp1251' | 'TIS-620' | 'KOI8-R'
CharacterSet ::= 'SET' Whitespace Encoding EOL

FLAG_LONG ::= 'num'
FLAG_NUM ::= 'long'
FLAG_UNI ::= 'UTF-8'
/* undefined FLAG_CHAR is the default */
Flag ::= 'FLAG' Whitespace ( FLAG_LONG | FLAG_NUM | FLAG_UNI ) EOL

Try ::= 'TRY' Whitespace EOL

Key ::= 'KEY' Whitespace EOL

WordChars ::= 'WORDCHARS' Whitespace EOL

AffixFile ::= Comment* CharacterSet? Comment* Flag? Comment* Try? Comment* Key? Comment* WordChars? Comment*
